#!/bin/bash
set -e

# create output if does not exist

if [ "$1" == "en" ]; then
	uv run rendercv render -nomd -nohtml -nopng -pdf="rendercv_output/wissam_benhaddad_cv_en.pdf" EN-Resume.yaml
else
	uv run rendercv render -nomd -nohtml -nopng -pdf="rendercv_output/wissam_benhaddad_cv_fr.pdf" FR-Resume.yaml
fi

# Keep only the PDF
find rendercv_output/ -type f ! -name "*.pdf" -delete

# Usage
# ./render.sh en
# ./render.sh fr
